//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_rental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class samochody
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public samochody()
        {
            this.wypozyczenia = new HashSet<wypozyczenia>();
        }
    
        public int Id_samochod { get; set; }
        public Nullable<int> Rocznik { get; set; }
        public Nullable<double> Silnik { get; set; }
        public Nullable<int> Id_marka { get; set; }
        public Nullable<int> Id_model { get; set; }
        public Nullable<System.DateTime> Data_rejestracji { get; set; }
        public Nullable<double> Cena { get; set; }
        public Nullable<int> Id_kategoria { get; set; }
    
        public virtual kategorie kategorie { get; set; }
        public virtual marki marki { get; set; }
        public virtual modele modele { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wypozyczenia> wypozyczenia { get; set; }
    }
}
